version: '3'
services:

  client:
    container_name: frontend
    build: ./client
    command: npm start
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
 
  server:
    container_name: backend
    build: ./server
    ports:
      - '4000:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'